### PR TITLE
Handle running as PID 1

### LINKED ISSUE #170: Sidecar produces zombies when git repo is unreachable
By default if git-sync is unable to reach git repo it fails which is causing pod failing. To avoid this I tried to use `-max-sync-failures=-1,` but in case of repo unavailability git-sync produces zombie processes and sometimes a huge amount of them.
In case of successful initial sync and `-max-sync-failures=-1` git-sync process shouldn't produce a child for each re-sync iteration in case repo is temporary unavailable.

**image:** k8s.gcr.io/git-sync:v3.1.1

```
65533    28507 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28508 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28509 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28510 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28515 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28517 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28518 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28520 24506  0 04:00 ?        00:00:00 [ssh] <defunct>
65533    28524 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28527 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28528 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28529 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28530 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28531 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28533 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28535 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28540 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28541 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28543 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28544 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28549 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28550 24506  0 May14 ?        00:00:00 [ssh] <defunct>
65533    28553 24506  0 May13 ?        00:00:00 [ssh] <defunct>
65533    28554 24506  0 May11 ?        00:00:00 [ssh] <defunct>
65533    28561 24506  0 May14 ?        00:00:00 [ssh] <defunct>
...
```
After 5 days running:
```
$ ps -ef | grep defunct | wc -l 
18091
```

### PR DESCRIPTION
**Pull request by thockin**
This detects when it is running as pid 1, and becomes an init process.
Specifically this means handling SIGCHLD and reaping processes
(otherwise they become zombies) and forwarding signals to "real"
process.
    
We fork and re-exec ourselves so that we only get *this* SIGCHLD for
orphaned processes (re-parented to 1) and not the real events from
running things like git or ssh.

Fixes #170

### CODE REVIEW

File: pkg/pid1/pid1.go [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+		return err
+	}
+	cmd := exec.Command(bin, os.Args[1:]...)
+	cmd.Stdin = os.Stdin
+	cmd.Stdout = os.Stdout
+	cmd.Stderr = os.Stderr
+	if err := cmd.Start(); err != nil {
+		return err
+	}
+	go runInit(cmd.Process.Pid)
```
Comment (stp-ip) [inline pkg/pid1/pid1.go]: Why run as a go routine?

**Comment by thockin** [comment]
I want the init process to proceed, but the re-exec'ed command to be waited
for.  When cmd exits, the caller (main) will Exit.

I guess we could put the os.Exit() in pid1, but that felt wrong.  In this
case it does leak a goroutine if the parent does not exit...

**Comment by stp-ip** [comment]
Would prefer a one line comment on the edge case of the go routine leaking. Besides this.
/lgtm

**Comment by thockin** [comment]
Comments updated and moved Exit handling into pid1.
