### PR TITLE
git-sync: removes special exit on first error

### LINKED ISSUE #161: Add an option to keep retrying even if first sync attempt fails
I'd like to have a settable option by which `git-sync` will not abort on a failed first `git sync` attempt, but would keep retrying.

This seems a bit counter-intuitive.  I've found, however, that restarting a git-sync deployment that is seeing a transient error is less confusing than a git-sync that has reached a full 5 minute backoff delay and then gets fixed -- because if you are not careful you may miss the fact that you are seeing a backed-off git-sync.

In practice, we end up power-cycling git-sync anyways.  At which point, we may as well keep git-sync up and running.

Long story short, PR upcoming.

### PR DESCRIPTION
**Pull request by filmil**
Old code used to exit at any error seen on first sync attempt.  This
didn't prove useful in practice, so removing that special case.

This may make git-sync slower to recover after user fixes a
non-retryable error, as now flMaxSyncFailures are needed before the pod
fails.  It may make sense in practice.

Fixes #161, in a different way than is proposed in PR #162.

### CODE REVIEW

File: cmd/git-sync/main.go [hunk 1]
```diff
@@ -289,7 +289,8 @@ func main() {
 		if changed, err := syncRepo(ctx, *flRepo, *flBranch, *flRev, *flDepth, *flRoot, *flDest); err != nil {
 			syncDuration.WithLabelValues("error").Observe(time.Now().Sub(start).Seconds())
 			syncCount.WithLabelValues("error").Inc()
-			if initialSync || (*flMaxSyncFailures != -1 && failCount >= *flMaxSyncFailures) {
```
Comment (thockin) [inline cmd/git-sync/main.go]: Can we get rid of the initialSync variable entirely now?

Comment (thockin) [reply cmd/git-sync/main.go]: Oops, no we can't
