### PR TITLE
Make relative-path submodules work, via origin

### LINKED ISSUE #763: Submodules with relative path fail to clone
Running v4.0.0-rc2 as a k8s sidecar container.

git-sync worked great until I added a submodule to my repo.  It then started failing & repeatedly restarting; looks like the root cause is that the git submodule commands are interpreting the relative path in .gitmodules as relative to the filesystem rather than relative to the original clone address (HTTPS).

Logs:
```
INFO: detected pid 1, running init handler
{"logger":"","ts":"2023-07-05 17:51:28.211056","caller":{"file":"main.go","line":720},"level":0,"msg":"starting up","pid":11,"uid":472,"gid":472,"home":"/tmp","flags":["--add-user=false","--change-permissions=0","--cookie-file=false","--depth=1","--exechook-backoff=3s","--exechook-timeout=30s","--git=git","--git-gc=always","--group-write=false","--help=false","--http-metrics=false","--http-pprof=false","--link=REDACTED_ROOT_REPO.git","--man=false","--max-failures=0","--max-sync-failures=0","--one-time=false","--password=REDACTED","--period=30s","--ref=HEAD","--repo=https://REDACTED_SERVER/REDACTED_ROOT_PATH/REDACTED_ROOT_REPO.git","--root=/git","--ssh=false","--ssh-key-file=/etc/git-secret/ssh","--ssh-known-hosts=true","--ssh-known-hosts-file=/etc/git-secret/known_hosts","--stale-worktree-timeout=0s","--submodules=recursive","--sync-timeout=2m0s","--timeout=0","--username=REDACTED_DEPLOY_TOKEN_USER","--v=-1","--verbose=0","--version=false","--wait=0","--webhook-backoff=3s","--webhook-method=POST","--webhook-success-status=200","--webhook-timeout=1s"]}
{"logger":"","ts":"2023-07-05 17:51:28.607087","caller":{"file":"main.go","line":1760},"level":0,"msg":"update required","ref":"HEAD","local":"REDACTED_LOCAL_SHA","remote":"REDACTED_REMOTE_SHA","syncCount":0}
{"logger":"","ts":"2023-07-05 17:51:29.015793","caller":{"file":"main.go","line":969},"msg":"too many failures, aborting","error":"Run(git submodule update --init --recursive --depth 1): exit status 1: { stdout: \"\", stderr: \"fatal: repository '/git/REDACTED_SUBMODULE_PATH/REDACTED_SUBMODULE_REPO.git' does not exist\\nfatal: clone of '/git/REDACTED_SUBMODULE_PATH/REDACTED_SUBMODULE_REPO.git' into submodule path '/git/.worktrees/REDACTED_REMOTE_SHA/REDACTED_SUBMODULE_REPO' failed\\nFailed to clone 'REDACTED_SUBMODULE_REPO'. Retry scheduled\\nfatal: repository '/git/REDACTED_SUBMODULE_PATH/REDACTED_SUBMODULE_REPO.git' does not exist\\nfatal: clone of '/git/REDACTED_SUBMODULE_PATH/REDACTED_SUBMODULE_REPO.git' into submodule path '/git/.worktrees/REDACTED_REMOTE_REPO/REDACTED_SUBMODULE_REPO' failed\\nFailed to clone 'REDACTED_SUBMODULE_REPO' a second time, aborting\" }","failCount":1}
```

.gitmodules file:

```
[submodule "REDACTED_SUBMODULE_REPO"]
	path = REDACTED_SUBMODULE_REPO
	url = ../../REDACTED_SUBMODULE_PATH/REDACTED_SUBMODULE_REPO.git
```

Luckily the submodule is not critical to the repo's contents, so my temporary work-around is to use `--submodules=off` on the sidecar container.

### PR DESCRIPTION
**Pull request by thockin**
The "origin" remote is implicitly used as the basis for relative-paths in submodules.  It's very subtly documented, and I have no idea if there are other places where it is used.  It seems git really expects it to exist, so let's just do that.

Fixes #763

### CODE REVIEW

File: pkg/cmd/cmd.go [hunk 1]
```diff
@@ -80,10 +81,10 @@ func runWithStdin(ctx context.Context, log logintf, cwd string, env []string, st
 	stdout := strings.TrimSpace(outbuf.String())
 	stderr := strings.TrimSpace(errbuf.String())
 	if ctx.Err() == context.DeadlineExceeded {
-		return "", "", fmt.Errorf("Run(%s): %w: { stdout: %q, stderr: %q }", cmdStr, ctx.Err(), stdout, stderr)
+		return stdout, stderr, fmt.Errorf("Run(%s): %w: { stdout: %q, stderr: %q }", cmdStr, ctx.Err(), stdout, stderr)
```
Comment (justinsb) [inline pkg/cmd/cmd.go:84]: TIL %w does not have to be the last arg!

**Comment by thockin** [comment]
Justin pointed out by chat that the set-url logic will not be run because the "normal" success path does early return.  Easy fix, running e2e now

**Comment by thockin** [comment]
PTAL :)

**Comment by justinsb** [comment]
Thanks @thockin :-)

/lgtm
