### PR TITLE
Fix exit non-zero exit codes when running as pid1

### LINKED ISSUE #314: Change the 'rev-' directory name instead of creating a symlink
Hi, 
I would like to ask you if there is any chance to change the directory name instead of creating a symlink. 
I am trying to use the **git-sync** tool together with [kaniko](https://github.com/GoogleContainerTools/kaniko) (a tool to build the docker files). Unfortunately, docker command `COPY` sees this symlink as a file, and instead of copying all files from inside of a directory, it copies only symlink as a single file. check my issue [1513](https://github.com/GoogleContainerTools/kaniko/issues/1513)

Currently with flags `GIT_SYNC_ROOT=/github` and `GIT_SYNC_DEST=repo` is created symlink `repo` inside directory `/github`

```sh
/github # ls -la
total 8
drwxr-xr-x    1 root     root            22 Jan  1   1970 .
drwxr-xr-x    1 root     root           140 Dec  3 15:53 ..
lrwxrwxrwx  1 root     root            44 Jan  1  1970 repo -> rev-249971a4b53a2a32ca573cd512a53d6a8cf15e78
drwxr-xr-x    1 root     root          345 Jan  1  1970 rev-249971a4b53a2a32ca573cd512a53d6a8cf15e78
``` 
I am not able to use the current name of the directory `rev-249971a4b53a2a32ca573cd512a53d6a8cf15e78` because it will change on each commit, so it's impossible to automate the build process for docker image. 

I am open to any suggestions.
br

### LINKED ISSUE #339: non zero return code not respected inside kubernetes pod init container
I am running the image as kubernetes pod init container, which seems to be even return 0 (success) if the git-sync fails with non zero return codes.
From pods descrive status section
  ```
- containerID: docker://55c2100d7a11b2e3c9bce8daacabd5b2b75257cb0fe189857b70e82e95645b43
    image: XXXXXXXXXXXXXX/git-sync:v3.2.2
    imageID: docker-pullable://XXXXXXXXXXXXXXXX/git-sync@sha256:85d203d29623d5e7489751812d628e29d0e22075c94a2e99681ecf70be3977ad
    lastState: {}
    name: git-sync
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://55c2100d7a11b2e3c9bce8daacabd5b2b75257cb0fe189857b70e82e95645b43
        exitCode: 0
        finishedAt: "2021-02-23T06:27:28Z"
        reason: Completed
        startedAt: "2021-02-23T06:27:25Z"
```

deployment.yaml sectio:
```
      initContainers:
        - image: {{ include "image.gitsync" . }}
          name: git-sync
          volumeMounts:
            - name: model-repository
              mountPath: {{ .Values.gitsync.folderpath }}
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 500m
              memory: 500Mi
              ephemeral-storage: 1Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: GIT_SYNC_REPO
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}.models
                  key: repo
            - name: GIT_SYNC_ROOT
              value: {{ .Values.gitsync.folderpath }}
            - name: GIT_SYNC_DEST
              value: repository
            - name: GIT_SYNC_BRANCH
              value: {{ .Values.branch | required "A valid branch or tag for models called branch repo is required" }}
            - name: GIT_SYNC_REV
              value: {{ .Values.revision | required "A valid branch or tag for models called revision repo is required" }}
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
```

Below log states failed, even the init conatiner exists with status 0 and continues with regular pod to start, what shall not happen.
Instead the init container shall return code 128 and fail with init and so fail the whole pod as expected.
kubectl logs XXXXXXX-5f9c474675-mg5kc -c git-sync -nnonprod
```
INFO: detected pid 1, running init handler
I0223 06:27:25.213737      11 main.go:430]  "level"=0 "msg"="starting up"  "args"=["/git-sync"] "pid"=11
I0223 06:27:25.214058      11 main.go:694]  "level"=0 "msg"="cloning repo"  "origin"="https://anyuser:SECRET@dev.azure.com/XXXXX/XXXXX/_git/XXXXXX" "path"="/tmp/git"
E0223 06:27:28.438939      11 main.go:455]  "msg"="too many failures, aborting" "error"="Run(git rev-parse 65f08a7): exit status 128: { stdout: \"65f08a7\\n\", stderr: \"fatal: ambiguous argument '65f08a7': unknown revision or path not in the working tree.\\nUse '--' to separate paths from revisions, like this:\\n'git \u003ccommand\u003e [\u003crevision\u003e...] -- [\u003cfile\u003e...]'\\n\" }"  "failCount"=0
```

I assume thta even the clone of branch failed and it still tries to change to revision GIT_SYNC_REV afterwards based on an invalid failed local cloned repo. Please check if the fail of GIT_SYNC_REV change might not be exported as return code . 
Or is there anything why i need to do different to use the container to get failed in that case too?

Maybe GIT_SYNC_DEPTH 1 is pruning history and so for unusable together with GIT_SYNC_REV which might be prunned?

### PR DESCRIPTION
**Pull request by thockin**
Prior to this we would swallow the exit code and always exit(0).

Fixes #339 

Fixes #314

### CODE REVIEW

File: pkg/pid1/pid1.go [hunk 1]
```diff
@@ -11,60 +11,73 @@ import (
...
 		}
 	}
+	return 0, fmt.Errorf("signal handler terminated unexpectedly")
 }
 
-// sigchld handles a SIGCHLD.  This will return true when firstborn exits.  In
-// case of truly unknown errors it will panic.
-func sigchld(firstborn int) bool {
+// sigchld handles a SIGCHLD.  This will return true only when firstborn exits.
+// For any other process thihs will return false and a 0 status.
```
Comment (stp-ip) [inline pkg/pid1/pid1.go:63]:
```suggestion
// For any other process this will return false and a 0 status.
```

**Review by stp-ip — APPROVED** [review]
/approve

Small nit/typo
